---
development:
  cloud_name: hlax0szmq
  api_key: '582575777785746'
  api_secret: F5k7eq_2v5a4ffazI8LXiqBg_Yk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hlax0szmq
  api_key: '582575777785746'
  api_secret: F5k7eq_2v5a4ffazI8LXiqBg_Yk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hlax0szmq
  api_key: '582575777785746'
  api_secret: F5k7eq_2v5a4ffazI8LXiqBg_Yk
  enhance_image_tag: true
  static_image_support: false
